version: '3'

services:
    lilith:
        build: .
        container_name: lilith
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        volumes:
            - ./data/campus/campus4-c0.avi:/usr/src/app/data/campus/campus4-c0.avi:ro
            - ./data/campus/campus4-c1.avi:/usr/src/app/data/campus/campus4-c1.avi:ro
            - ./data/campus/campus4-c2.avi:/usr/src/app/data/campus/campus4-c2.avi:ro
            - ./weights/yolov7.pt:/usr/src/app/weights/yolov7.pt:ro
            - ./weights/osnet_x0_75_msmt17.pt:/usr/src/app/weights/osnet_x0_75_msmt17.pt:ro
        env_file:
            - .env
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]

    influxdb:
        image: influxdb:2.6.1-alpine
        container_name: influxdb
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        volumes:
            - influxdb_data:/var/lib/influxdb2
        ports:
            - 8086:8086/tcp

    rtmp-server:
        image: alqutami/rtmp-hls:latest-alpine
        container_name: rtmp-server
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        ports:
            - 1935:1935/tcp

volumes:
    influxdb_data:
