version: '3'

services:
    moni:
        build: .
        container_name: moni
        profiles: ['moni', 'dev']
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        volumes:
            - ./conf/docker-config.yml:/usr/src/app/config.yml:ro
            - ./weights/yolov7.pt:/usr/src/app/weights/yolov7.pt:ro
            - ./weights/osnet_x0_75_msmt17.pt:/usr/src/app/weights/osnet_x0_75_msmt17.pt:ro
            - ./data/campus/campus4-c0.avi:/usr/src/app/data/campus/campus4-c0.avi:ro
            - ./data/campus/campus4-c1.avi:/usr/src/app/data/campus/campus4-c1.avi:ro
            - ./data/campus/campus4-c2.avi:/usr/src/app/data/campus/campus4-c2.avi:ro
            - ./output:/usr/src/app/output
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]

    influxdb:
        image: influxdb:2.6.1-alpine
        container_name: influxdb
        profiles: ['influxdb', 'dev']
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        volumes:
            - influxdb_data:/var/lib/influxdb2
        ports:
            - 8086:8086/tcp

    rtsp:
        image: aler9/rtsp-simple-server
        container_name: rtsp
        profiles: ['rtsp', 'dev']
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        ports:
            - 8554:8554/tcp

volumes:
    influxdb_data:
