version: '3'

services:
    lilith:
        build: .
        container_name: lilith
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        volumes:
            - C:\Users\thoma\Documents\Projects\Lilith-FlowTracker\data\campus\campus4-c0.avi:/usr/src/app/data/campus/campus4-c0.avi:ro
            - C:\Users\thoma\Documents\Projects\Lilith-FlowTracker\data\campus\campus4-c1.avi:/usr/src/app/data/campus/campus4-c1.avi:ro
            - C:\Users\thoma\Documents\Projects\Lilith-FlowTracker\data\campus\campus4-c2.avi:/usr/src/app/data/campus/campus4-c2.avi:ro
            - C:\Users\thoma\Documents\Projects\Lilith-FlowTracker\weights\osnet_x0_25_msmt17.pt:/usr/src/app/weights/osnet_x0_25_msmt17.pt:ro
            - C:\Users\thoma\Documents\Projects\Lilith-FlowTracker\weights\yolov7x.pt:/usr/src/app/weights/yolov7x.pt:ro
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
