version: '3'

services:
    lilith:
        build: .
        container_name: lilith
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        volumes:
            - ./data/campus/campus4-c0.avi:/usr/src/app/data/campus/campus4-c0.avi:ro
            - ./data/campus/campus4-c1.avi:/usr/src/app/data/campus/campus4-c1.avi:ro
            - ./data/campus/campus4-c2.avi:/usr/src/app/data/campus/campus4-c2.avi:ro
        env_file:
            - .env
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
