config:
    influxdb:
        enable: True
        url: http://localhost:8086
        token: SECRET
        org: hackathon-thurgau
        bucket: position_data

    strongsort:
        ecc: False
        mc_lambda: 0.995
        ema_alpha: 0.9
        max_dist: 0.2
        max_iou_distance: 0.7
        max_age: 1000
        n_init: 3
        nn_budget: 100

    hardware:
        device_1: 0
        device_2: 1
        device_3: 2

    stream:
        input:
            video_1: './data/campus/campus4-c0.avi'
            video_2: './data/campus/campus4-c1.avi'
            video_3: './data/campus/campus4-c2.avi'
        output:
            enable: True
            video_1: 'rtmp://localhost:1935/live/588fa378-3ac9-4abb-bb3a-7539ce0b0821'
            video_2: 'rtmp://localhost:1935/live/588fa378-3ac9-4abb-bb3a-7539ce0b0822'
            video_3: 'rtmp://localhost:1935/live/588fa378-3ac9-4abb-bb3a-7539ce0b0823'

    processing:
        show_video: False
        show_matplot: False
